# Claude API config
claude.api.url=https://api.anthropic.com
claude.model = claude-3-5-haiku-20241022

# Qdrant config
vectordb.url=http://localhost:6333


# AWS configuration
aws.region=ap-northeast-3

# MongoDB configuration for IntelliSnap
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=techSnap
spring.data.mongodb.username=beam
spring.data.mongodb.password=beam

# Redis cache config
spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=6379



